{% set name = "tatc" %}
{% set version = "3.4.7" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/code-lab-org/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8a08b4ff78560d875695da88b3420a96d38187b44166b452c4578854aec49cb4

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - geopandas >=0.13.2
    - numba
    - numpy
    - pandas
    - pydantic >=2.6
    - pyyaml
    - shapely >=2
    - skyfield >=1.48
    - sgp4
    - spiceypy

test:
  source_files:
    - tests
  imports:
    - tatc
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - python -m unittest

about:
  home: https://github.com/code-lab-org/tatc
  summary: 'Tradespace Analysis Toolkit for Constellations (TAT-C)'
  description: |
    tatc provides low-level data structures and analysis functions for systems
    engineering design and trades of Earth-observing space systems with a
    focus on distributed missions and constellations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://tatc.readthedocs.io/
  dev_url: https://github.com/code-lab-org/tatc

extra:
  recipe-maintainers:
    - ptgrogan
